### ISSUE TITLE
Social Media Preview showing GDG LVIV instead of GDG Spacecoast (or something local) 

### ISSUE THREAD

**Issue by ChristineKapp** [DevFestFlorida/DevFestFloridaSite#21]
When the link to the DevFest Florida site is shared on Facebook, the preview that is showing up when you type http://www.devfestflorida.org has a byline - "DEVFESTFLORIDA.ORG|BY OLEH ZASADNYY, GDG LVIV " - can this be updated to something closer to Florida?

**Comment by Splaktar** [comment]
This is fixed and deployed, but it looks like it will take some time for the previously cached data to clear out and for Facebook to load properly.

**Comment by ChristineKapp** [comment]
Hi

Cool! Thanks.  I just used the Facebook cache debugger on zenverse to clear
it out and it now says "By Michael Traverso and Michael Prentice" :-)

Christi
