### ISSUE TITLE
Code of Conduct link goes no where

### ISSUE THREAD

**Issue by Splaktar** [DevFestFlorida/DevFestFloridaSite#3]
We'll want to get a CoC page up prior to the event and likely before promoting ticket sales to make the event appealing to a diverse group of people.

This can be used as a reference:
http://gdg-x.github.io/boomerang/#!/conduct

**Comment by miketraverso** [comment]
See pull request #6

**Comment by Splaktar** [comment]
PR #6 includes a brief CoC, but I'd like to include the Anti-Harassment and Values sections in that post at some point as well.

**Comment by miketraverso** [comment]
If one of the other organizers can take this then great. Otherwise I think we meet the requirements as while brief, there is a link to the full Code of Conduct. It's a feature not a bug.

**Comment by Splaktar** [comment]
Fixed in https://github.com/DevFestFlorida/DevFestFloridaSite/commit/ab812921050e0a51a80e13f9994632ab818a354d
